### ISSUE TITLE
reference to CooRTweet

### ISSUE THREAD

**Issue by nicolarighetti** [Zack9961/CooRnet.powered.by.CooRTweet#1]
Hi Alessandro, thanks for using CooRTweet, we are glad it is useful. We kindly ask you to cite the package in the references, using the following format:

> Righetti N, Balluff P (2023). CooRTweet: Coordinated Networks Detection on Social Media. R package version 2.0.0, <https://github.com/nicolarighetti/CooRTweet>.

A link to the original repository would also be appreciate.

If you have any suggestions to improve it please let us know! Thanks again for the interest.

Nicola

**Comment by Zack9961** [comment]
Hi Nicola,

Thank you for your message and for creating the CooRTweet package. I sincerely apologize for not properly citing your package in my forked version of CooRnet. I will add the citation in my work using the format you kindly provided and include the link to your repository.

I appreciate your work, and if I have any suggestions to improve the package, I will not hesitate to share them with you.

Thank you again for your interest and support.

Best regards,
Alessandro
